### ISSUE TITLE
AttributeError: module 'jax' has no attribute 'tree'

### ISSUE THREAD

**Issue by TianleLiu0303** [SilviaSapora/evil#1]
Visible devices [StreamExecutorGpuDevice(id=0, process_index=0, slice_index=0)]
Traceback (most recent call last):
  File "/home/ltl/My_Projects_Python/IRL/evil/evil/scripts/run_irl.py", line 30, in <module>
    run_irl(irl_config)
  File "/home/ltl/My_Projects_Python/IRL/evil/evil/irl/run_irl.py", line 76, in run_irl
    env, env_params, original_training_config = get_env(
  File "/home/ltl/My_Projects_Python/IRL/evil/evil/utils/env_utils.py", line 23, in get_env
    env, env_params = BraxGymnaxWrapper(env_name, backend=backend), None
  File "/home/ltl/My_Projects_Python/IRL/evil/evil/training/wrappers.py", line 136, in __init__
    env = envs.get_environment(env_name=env_name, backend=backend)
  File "/home/ltl/anaconda3/envs/evil/lib/python3.10/site-packages/brax/envs/__init__.py", line 63, in get_environment
    return _envs[env_name](**kwargs)
  File "/home/ltl/anaconda3/envs/evil/lib/python3.10/site-packages/brax/envs/ant.py", line 162, in __init__
    sys = mjcf.load(path)
  File "/home/ltl/anaconda3/envs/evil/lib/python3.10/site-packages/brax/io/mjcf.py", line 519, in load
    return load_model(mj)
  File "/home/ltl/anaconda3/envs/evil/lib/python3.10/site-packages/brax/io/mjcf.py", line 346, in load_model
    link = jax.tree.map(lambda x: x[1:].copy(), link)
AttributeError: module 'jax' has no attribute 'tree'

**Comment by SilviaSapora** [comment]
This seems to be an issue with a wrong version of JAX. Just update the JAX version to something more recent
